In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [5]:
df.shape[0]

2160

In [39]:
df['Brand'].nunique()

27

In [31]:
df.isna().any().sum()

np.int64(3)

In [32]:
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [37]:
df['Final Price']..max()

np.float64(7150.47)

In [38]:
df[df['Brand'] == 'Dell']['Final Price'].max()

np.float64(3936.0)

In [40]:
median_before = df['Screen'].median()
print("Median before filling:", median_before)

Median before filling: 15.6


In [41]:
most_frequent = df['Screen'].mode()[0]
print("Most frequent value:", most_frequent)

Most frequent value: 15.6


In [42]:
df['Screen'] = df['Screen'].fillna(most_frequent)

In [43]:
median_after = df['Screen'].median()
print("Median after filling:", median_after)

Median after filling: 15.6


In [46]:
df_weights = df[df['Brand']=='Innjoo'][['RAM','Storage','Screen']]

In [48]:
df_weights.head()

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1

In [49]:
import numpy as np

X = df_weights.to_numpy()  # This is your feature matrix


In [50]:
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [51]:
XTX = X.T @ X

In [52]:
XTX_inv = np.linalg.inv(XTX)

In [53]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [54]:
w = XTX_inv @ X.T @ y

In [55]:
result = w.sum()
print("Sum of elements in w:", result)

Sum of elements in w: 91.2998806299555
